###########################################
###########################################
###########################################
##### wemos_07_dining_room_light.yaml #####
###########################################

  - platform: mqtt
    name: "Dining Room Light"
    state_topic: "Wemos_07/stat/POWER1"
    command_topic: "Wemos_07/cmnd/POWER1"
    availability_topic: "Wemos_07/tele/LWT"
    qos: 1
    payload_on: "OFF"
    payload_off: "ON"
    payload_available: "Online"
    payload_not_available: "Offline"
    retain: true
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###