###########################################
###########################################
###########################################
###### custom_next_rocket_launch.yaml #####
###########################################
- platform: next_rocket_launch
  rocket_name:
    - "ALL"
#    - "Ariane"
#    - "Falcon"
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###