###########################################
###########################################
###########################################
############ hassio_uptime.yaml ###########
###########################################
- platform: uptime
  name: 'Hassio Uptime'
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###