###########################################
###########################################
###########################################
############ hassio_uptime.yaml ###########
###########################################
- platform: launch_library
  name: Launch Library
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###