###########################################
###########################################
###########################################
######### ups_apc600_minutes.yaml #########
###########################################

- platform: template
  sensors:
    ups_apc600_battery_runtime_minutes:
      value_template: '{{ ((states.sensor.ups_apc600_battery_runtime_seconds.state | float * 1 / 60)) | round(2) }}'

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################