###########################################
###########################################
###########################################
#### zwave_driveway_motion_sensor.yaml ####
###########################################
- platform: template
  sensors:
    duke_energy_cost_kwh_fee:
      friendly_name: "Duke Energy per kWh"
      unit_of_measurement: 'USD'
      value_template: "{{ ('0.1001348') | float }}"
###########################################
- platform: template
  sensors:
    duke_energy_bill_daily:
      friendly_name: "Today's Energy Bill"
      unit_of_measurement: 'USD'
      value_template: "{{ states('sensor.total_energy_usage_daily') | float * states('sensor.duke_energy_cost_kwh_fee') | float | round(2) | float }}"
###########################################
- platform: template
  sensors:
    duke_energy_bill_monthly:
      friendly_name: "Monthly Energy Bill"
      unit_of_measurement: 'USD'
      value_template: "{{ states('sensor.total_energy_usage_monthly') | float * states('sensor.duke_energy_cost_kwh_fee') | float | round(2) | float }}"
###########################################
#- platform: template
#  sensors:
#    duke_energy_bill_quarterly:
#      friendly_name: "Quarterly Energy Bill"
#      unit_of_measurement: 'USD'
#      value_template: "{{ states('sensor.total_energy_usage_quarterly') | float * states('sensor.duke_energy_cost_kwh_fee') | float | round(2) }}"
###########################################
#- platform: template
#  sensors:
#    duke_energy_bill_annually:
#      friendly_name: "Annual Energy Bill"
#      unit_of_measurement: 'USD'
#      value_template: "{{ states('sensor.total_energy_usage_annually') | float * states('sensor.duke_energy_cost_kwh_fee') | float | round(2) }}"
###########################################
###########################################
###########################################
###########################################
###########################################
###########################################
###########################################
###########################################
###########################################
###########################################
###########################################
###########################################
- platform: template
  sensors:
    energy_cost_master_bedroom_heater_daily:
      friendly_name: "Master Heater (Today)"
      unit_of_measurement: 'USD'
      value_template: "{{ states('sensor.master_bedroom_heater_kwh_today') | float * states('sensor.duke_energy_cost_kwh_fee') | float | round(2) }}"
- platform: template
  sensors:
    energy_cost_master_bedroom_heater_total:
      friendly_name: "Master Heater (Total)"
      unit_of_measurement: 'USD'
      value_template: "{{ states('sensor.master_bedroom_heater_kwh_total') | float * states('sensor.duke_energy_cost_kwh_fee') | float | round(2) }}"
###########################################
###########################################
###########################################
- platform: template
  sensors:
    energy_cost_washing_machine_daily:
      friendly_name: "Washing Machine (Today)"
      unit_of_measurement: 'USD'
      value_template: "{{ states('sensor.washing_machine_kwh_today') | float * states('sensor.duke_energy_cost_kwh_fee') | float | round(2) }}"
- platform: template
  sensors:
    energy_cost_washing_machine_total:
      friendly_name: "Washing Machine (Total)"
      unit_of_measurement: 'USD'
      value_template: "{{ states('sensor.washing_machine_kwh_total') | float * states('sensor.duke_energy_cost_kwh_fee') | float | round(2) }}"
###########################################
###########################################
###########################################
- platform: template
  sensors:
    energy_cost_kitchen_refrigerator_daily:
      friendly_name: "Kitchen Refrigerator (Today)"
      unit_of_measurement: 'USD'
      value_template: "{{ states('sensor.kitchen_refrigerator_kwh_today') | float * states('sensor.duke_energy_cost_kwh_fee') | float | round(2) }}"
- platform: template
  sensors:
    energy_cost_kitchen_refrigerator_total:
      friendly_name: "Kitchen Refrigerator (Total)"
      unit_of_measurement: 'USD'
      value_template: "{{ states('sensor.kitchen_refrigerator_kwh_total') | float * states('sensor.duke_energy_cost_kwh_fee') | float | round(2) }}"
###########################################
###########################################
###########################################
- platform: template
  sensors:
    energy_cost_z420_server_daily:
      friendly_name: "Z420 Server (Today)"
      unit_of_measurement: 'USD'
      value_template: "{{ states('sensor.z420_server_kwh_today') | float * states('sensor.duke_energy_cost_kwh_fee') | float | round(2) }}"
- platform: template
  sensors:
    energy_cost_z420_server_total:
      friendly_name: "Z420 Server (Total)"
      unit_of_measurement: 'USD'
      value_template: "{{ states('sensor.z420_server_kwh_total') | float * states('sensor.duke_energy_cost_kwh_fee') | float | round(2) }}"
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###