###########################################
###########################################
###########################################
############## calendar.yaml ##############
###########################################
- platform: caldav
  username: !secret icloud_username
  password: !secret icloud_password
  url: !secret icloud_calendar_url
  calendars: 
    - "Tiffany & Steven"
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###