###########################################
###########################################
###########################################
############## climate.yaml ###############
###########################################

- platform: honeywell
  username: !secret Honeywell_TCC_USER
  password: !secret Honeywell_TCC_PASS
#  region: us

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###