###########################################
###########################################
###########################################
############## coinbase.yaml ##############
###########################################
api_key: Coinbase_API_Key
api_secret: Coinbase_API_Secret
account_balance_currencies:
  - XTZ
  - BTC
  - LTC
  - ETH
  - BAT
#exchange_rate_currencies:
#  - BTC
#  - ETH
#  - LTC
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################