###########################################
###########################################
###########################################
########## device_trackers.yaml ###########
###########################################

- platform: virtual
  devices:
    - sdm_device_tracker_01
    - sdm_device_tracker_02
    - sdm_device_tracker_03
    - sdm_device_tracker_04
    - sdm_device_tracker_05
    - sdm_device_tracker_06
    - sdm_device_tracker_07
    - sdm_device_tracker_08
    - sdm_device_tracker_09
    - sdm_device_tracker_10

- platform: nmap_tracker
  hosts:
    - 10.1.1.53
    - 10.1.1.57
    - 10.1.1.61
    - 10.1.1.62
    - 10.1.1.64
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################