###########################################
###########################################
###########################################
############### groups.yaml ###############
###########################################

sirens:
  name: Sirens
  icon: mdi:alarm-light
  all: false
  entities:
    - switch.living_room_siren
    - switch.master_bedroom_siren
    - switch.hallway_siren
###########################################
windows:
  name: Windows
  icon: mdi:window-closed-variant
  all: false
  entities:
    - binary_sensor.kitchen_window
    - binary_sensor.nursery_window
    - binary_sensor.hallway_bathroom_window
    - binary_sensor.master_bathroom_window
    - binary_sensor.left_living_room_window
    - binary_sensor.right_living_room_window
    - binary_sensor.left_guest_bedroom_window
    - binary_sensor.right_guest_bedroom_window
###########################################
living_room_lamps:
  name: Living Room Lamps
  icon: mdi:lamp
  all: false
  entities:
    - switch.living_room_recliner_lamp
    - switch.living_room_entry_lamp
    - switch.living_room_floor_lamp
###########################################
interior_motion_sensors:
  name: Interior Motion Sensors
  icon: mdi:motion-sensor
  all: false
  entities:
    - binary_sensor.kitchen_motion
    - binary_sensor.living_room_motion
    - binary_sensor.master_bedroom_closet_motion
    - binary_sensor.master_bedroom_motion
    - binary_sensor.nursery_motion
    - binary_sensor.hallway_motion
    - binary_sensor.dining_room_motion
##################################################
master_bedroom_lights:
  name: Master Bedroom Lights
  icon: mdi:power-on
  all: false
  entities:
    - switch.master_bedroom_ceiling_fan_lights
    - switch.master_bedroom_closet
    - switch.master_bedroom_recessed_lights
    - switch.stevens_night_stand_lamp
##################################################
master_bathroom:
  name: Master Bathroom
  icon: mdi:power-on
  all: false
  entities:
    - switch.master_bathroom_closet_light
    - switch.master_bathroom_exhaust
    - switch.master_bathroom_light
    - switch.master_bathroom_vanity
##################################################
guest_bathroom:
  name: Guest Bathroom
  icon: mdi:power-on
  all: false
  entities:
    - switch.guest_bathroom_vanity
    - switch.guest_bathroom_exhaust
    - switch.guest_bathroom_light
##################################################
nursery_lights:
  name: Nursery Lights
  icon: mdi:power-on
  all: false
  entities:
    - switch.nursery_ceiling_light
    - switch.nursery_closet_light
##################################################
living_room_lights:
  name: Nursery Lights
  icon: mdi:power-on
  all: false
  entities:
    - switch.living_room_recliner_lamp
    - switch.living_room_entry_lamp
    - switch.living_room_floor_lamp
    - light.living_room_tv_wled
    - light.living_room_ceiling_fan_lights
##################################################
kitchen_lights:
  name: Nursery Lights
  icon: mdi:power-on
  all: false
  entities:
    - switch.kitchen_light
    - switch.dining_room_light
    - light.kitchen_cabinet_wled
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################