###########################################
###########################################
###########################################
############## life360.yaml ###############
###########################################

driving_speed: 15
interval_seconds: 10
max_gps_accuracy: 200
max_update_wait:
  minutes: 15
show_as_state:
  - driving
  - moving
warning_threshold: 2
error_threshold: 3
accounts:
  - username: !secret Life360_Tracker_Username
    password: !secret Life360_Tracker_Password

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################