###########################################
###########################################
###########################################
############ media_players.yaml ###########
###########################################
#- platform: androidtv
#  name: Extra Fire Stick
#  host: 10.1.1.108
#  adb_server_ip: 127.0.0.1

#- platform: androidtv
#  name: Master Bedroom Fire Stick
#  host: 10.1.1.109
#  adb_server_ip: 127.0.0.1
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###