###########################################
###########################################
###########################################
############ configuration.yaml ###########
###########################################

homeassistant:
  name: Morgan Household
  unit_system: imperial
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml
  auth_providers:
    - type: homeassistant
  elevation: 246
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  time_zone: America/New_York
alarm_control_panel: !include directory/alarm_control_panel.yaml
automation: !include automations.yaml
automation old: !include_dir_merge_list directory/automations/
binary_sensor: !include_dir_merge_list directory/binary_sensors/
#camera: !include directory/cameras.yaml
climate: !include directory/climate.yaml
cloud: !include directory/system/nabucasa.yaml
config:
#device_tracker: !include directory/device_trackers.yaml
discovery:
ffmpeg:
frontend:
  themes: !include_dir_merge_named directory/themes/
group: !include directory/system/groups.yaml
history: !include directory/system/history.yaml
input_select: !include directory/input_select.yaml
life360: !include directory/life360.yaml
logbook:
#logbook: !include directory/system/logbook.yaml
logger: !include directory/system/logger.yaml
#map:
mobile_app:
notify: !include directory/system/notify.yaml
panel_iframe: !include directory/system/panel_iframes.yaml
person:
recorder: !include directory/system/recorder.yaml 
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include_dir_merge_list directory/sensors/
shell_command: !include directory/system/shell_commands.yaml
ssdp:
stream:
sun:
switch: !include_dir_merge_list directory/switches/
system_health:
tts:
  - platform: google_translate
updater:
#utility_meter: !include directory/utility_meter.yaml
weather: !include directory/weather.yaml
zeroconf:
zone: !include directory/system/zones.yaml
zwave:
  usb_path: /dev/serial/by-id/usb-0658_0200-if00
  network_key: !secret zwave_network_key

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
