###########################################
###########################################
###########################################
############ hassio_uptime.yaml ###########
###########################################

- platform: uptime
  name: 'Hassio Uptime (Hours)'
  unit_of_measurement: hours
###########################################
- platform: uptime
  name: 'Hassio Uptime (Days)'
  unit_of_measurement: days
###########################################
- platform: uptime
  name: 'Hassio Uptime (Minutes)'
  unit_of_measurement: minutes

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
