###########################################
###########################################
###########################################
######## kasa_washing_machine.yaml ########
###########################################

- platform: template
  sensors:
###########################################
    kasa_washing_machine_amps:
      friendly_name_template: "{{ states.switch.washing_machine.name}} Current"
      value_template: '{{ states.switch.washing_machine.attributes["current_a"] | float }}'
      unit_of_measurement: 'A'
###########################################
    kasa_washing_machine_watts:
      friendly_name_template: "{{ states.switch.washing_machine.name}} Current Consumption"
      value_template: '{{ states.switch.washing_machine.attributes["current_power_w"] | float }}'
      unit_of_measurement: 'W'
###########################################
    kasa_washing_machine_total_kwh:
      friendly_name_template: "{{ states.switch.washing_machine.name}} Total Consumption"
      value_template: '{{ states.switch.washing_machine.attributes["total_energy_kwh"] | float }}'
      unit_of_measurement: 'kWh'
###########################################
    kasa_washing_machine_volts:
      friendly_name_template: "{{ states.switch.washing_machine.name}} Voltage"
      value_template: '{{ states.switch.washing_machine.attributes["voltage"] | float }}'
      unit_of_measurement: 'V'
###########################################
    kasa_washing_machine_kwh_today:
      friendly_name_template: "{{ states.switch.washing_machine.name}} Todays Consumption"
      value_template: '{{ states.switch.washing_machine.attributes["today_energy_kwh"] | float }}'
      unit_of_measurement: 'kWh'

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
