###########################################
###########################################
###########################################
########## time_date_sensors.yaml #########
###########################################

- platform: time_date
  display_options:
    - 'time'
    - 'date'
#    - 'date_time'
    - 'time_date'
###########################################
- platform: worldclock
  time_zone: America/New_York

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
