###########################################
###########################################
###########################################
##### ups_cyberpower_1500_minutes.yaml ####
###########################################

- platform: template
  sensors:
    ups_cyberpower_1500_battery_runtime_minutes:
      value_template: '{{ ((states.sensor.ups_cyberpower_1500_battery_runtime_seconds.state | float * 1 / 60)) | round(2) }}'
#      '{{ ((states.sensor.ups_apc_600_battery_runtime.state | float * 1 / 60)) }}'

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
