###########################################
###########################################
###########################################
############# nws_alerts.yaml #############
###########################################

# https://alerts.weather.gov/
###########################################
- platform: nws_alerts
  zone_id: 'NCZ070'
  name: Gaston County
- platform: nws_alerts
  zone_id: 'NCZ071'
  name: Mecklenburg County

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
