###########################################
###########################################
###########################################
################ nmap.yaml ################
###########################################

- platform: ping
  host: !secret LAN_IP_058
  name: 'Phone: Seth Jenelle'
  count: 2
  scan_interval: 60
###########################################
- platform: ping
  host: !secret LAN_IP_059
  name: 'Tablet: Isabel Medders'
  count: 2
  scan_interval: 60
###########################################
- platform: ping
  host: !secret LAN_IP_060
  name: 'Printer: Epson XP-330'
  count: 2
  scan_interval: 253
###########################################
- platform: ping
  host: !secret LAN_IP_061
  name: 'Phone: Charles Whitley'
  count: 2
  scan_interval: 60
###########################################
#- platform: ping
#  host: !secret LAN_IP_064
#  name: 'UNUSED'
#  count: 2
#  scan_interval: 253
###########################################
- platform: ping
  host: !secret LAN_IP_065
  name: 'Phone: Kayla Elkovich'
  count: 2
  scan_interval: 60
###########################################
- platform: ping
  host: !secret LAN_IP_066
  name: 'Phone: Beth Morgan'
  count: 2
  scan_interval: 60
###########################################
- platform: ping
  host: !secret LAN_IP_067
  name: 'Onkyo: Living Room'
  count: 2
  scan_interval: 60
###########################################
- platform: ping
  host: !secret LAN_IP_068
  name: 'Onkyo: MBR (Wi-Fi)'
  count: 2
  scan_interval: 253
###########################################
- platform: ping
  host: !secret LAN_IP_069
  name: 'Onkyo: MBR (Wired)'
  count: 2
  scan_interval: 253
###########################################
- platform: ping
  host: !secret LAN_IP_100
  name: 'Amazon: Echo Show 8'
  count: 2
  scan_interval: 253
###########################################
- platform: ping
  host: !secret LAN_IP_101
  name: 'Amazon: Living Room Echo'
  count: 2
  scan_interval: 253
###########################################
- platform: ping
  host: !secret LAN_IP_102
  name: 'Amazon: Kitchen Echo Dot'
  count: 2
  scan_interval: 253
###########################################
- platform: ping
  host: !secret LAN_IP_103
  name: 'Amazon: Nursery Echo Dot'
  count: 2
  scan_interval: 253
###########################################
- platform: ping
  host: !secret LAN_IP_131
  name: 'NodeMCU_01: Doors'
  count: 2
  scan_interval: 120
###########################################
- platform: ping
  host: !secret LAN_IP_132
  name: 'NodeMCU_02: Windows'
  count: 2
  scan_interval: 120
###########################################
- platform: ping
  host: !secret LAN_IP_133
  name: 'NodeMCU_03: Windows'
  count: 2
  scan_interval: 120
###########################################
- platform: ping
  host: !secret LAN_IP_200
  name: 'PC: HP Z420'
  count: 2
  scan_interval: 120
###########################################
- platform: ping
  host: !secret LAN_IP_210
  name: 'CCTV: Front Porch'
  count: 3
  scan_interval: 60
###########################################
- platform: ping
  host: !secret LAN_IP_211
  name: 'CCTV: Back Porch'
  count: 3
  scan_interval: 60
###########################################
- platform: ping
  host: !secret LAN_IP_212
  name: 'CCTV: Front Yard'
  count: 3
  scan_interval: 60
###########################################
- platform: ping
  host: !secret LAN_IP_213
  name: 'CCTV: Back Yard'
  count: 3
  scan_interval: 60
###########################################
- platform: ping
  host: !secret LAN_IP_224
  name: 'Phone: SDM'
  count: 2
  scan_interval: 68
###########################################
- platform: ping
  host: !secret LAN_IP_225
  name: 'iPad Air 2'
  count: 2
  scan_interval: 68
###########################################
- platform: ping
  host: !secret LAN_IP_240
  name: 'pfSense Gateway'
  count: 2
  scan_interval: 60
###########################################
- platform: ping
  host: !secret LAN_IP_241
  name: 'Netgear RAX200: Living Room'
  count: 2
  scan_interval: 120
###########################################
- platform: ping
  host: !secret LAN_IP_242
  name: 'Netgear R7000: Large Building'
  count: 2
  scan_interval: 120

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
