###########################################
###########################################
###########################################
###### wemos_11_dining_room_pir.yaml ######
###########################################

- platform: mqtt
  name: Dining Room Motion
#  state_topic: stat/Wemos_11/PIR1
  state_topic: Wemos_11/stat/PIR1
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
###########################################
# Rule2 on Switch2#state=1 do publish Wemos_11/stat/PIR1 ON endon on Switch2#state=0 do Publish Wemos_11/stat/PIR1 OFF endon

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
