###########################################
###########################################
###########################################
######### 02_theme_template.yaml ##########
###########################################
02_theme_template:
    primary-color: '#dd5800'
    disabled-text-color: '#242424'
    divider-color: 'rgba(255, 0, 0, 0.12)'
    ha-card-background: '#000000'
    paper-grey-200: '#4e4e4e'
    paper-item-icon-color: '#FFFFFF'
    paper-listbox-background-color: '#000000' #Input Select Drop Down, etc.
    paper-listbox-color: '#FFFFFF' # Contents of paper-listbox-background-color
    primary-background-color: '#2b2b2b' # For dialogs and popups...etc
    primary-text-color: '#dd5800'
    secondary-background-color: '#2b2b2b'
    secondary-text-color: '#dd5800'
    text-primary-color: 'var(--primary-text-color)'
    dark-primary-color: '#7a4901'
    light-primary-color: '#ff8f45'
    paper-toggle-button-checked-ink-color: '#ff8f45'
    paper-toggle-button-checked-button-color: '#00FF3C'
    paper-toggle-button-checked-bar-color: '#ff8f45'
    paper-slider-knob-color: '#dd5800'
    paper-slider-knob-start-color: '#dd5800'
    paper-slider-pin-color: '#dd5800'
    paper-slider-active-color: '#dd5800'
    paper-slider-secondary-color: '#ff8f45'
    label-badge-background-color: 'var(--secondary-background-color)'
    label-badge-text-color: 'var(--primary-text-color)'
    paper-card-header-color: '#var(--paper-item-icon-color)'
    paper-grey-50: 'var(--primary-text-color)'
    paper-item-icon-active-color: '#04FF00'
    paper-item-icon_-_color: 'var(--primary-text-color)'
    paper-toggle-button-unchecked-bar-color: 'var(--primary-text-color)'
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
# BLACK --------> #000000
# WHITE --------> #FFFFFF
# GRAY(S) ------> Lighter: #202020                    ---------------> Middle Range #727272                      ---------------> Darker: #383838 
# ORANGE(S) ----> #DD5800                             ---------------> 
# GREEN(S) -----> #04FF00 rgba(4, 255, 0, 0.8)        --------------->
# BLUE(S) ------>                                     ---------------> 
# RED(S) -------> Red: #FF0000 rgba(255, 0, 0, 1)     ---------------> Burgundyish: #900C3F rgba(144, 12, 63, 1) ---------------> 
# YELLOW(S) ----> #F7FF00                             ---------------> 
# PURPLE(S) ---->                                     ---------------> 
# BROWN(S) ----->                                     ---------------> 