people_glance:
  lovelace-background: 'Background-image'
  primary-text-color: 'rgba(255, 255, 255, 1)'
  secondary-text-color: '#727272'
  text-primary-color: '#ffffff'
  disabled-text-color: 'rgba(194, 194, 194, 1)'
  ###########################################################################
  # MAIN INTERFACE COLORS
  ###########################################################################
  primary-color: '#03a9f4'
  dark-primary-color: '#0288d1'
  light-primary-color: '#b3e5fC'
  accent-color: '#ff9800'
  card-color: 'rgba(17, 43, 187, 0.81)'
  ha-card-background: 'var(--card-color)'
  card-background-color: 'var(--card-color)'
  ###########################################################################
  divider-color: 'rgba(0, 0, 0, .12)'
  scrollbar-thumb-color: 'rgba(194, 194, 194, 1)'
  error-color: 'rgba(245, 0, 0, 1)'
  error-state-color: 'var(--error-color)'
  ################################## CARDS ##################################
  ha-card-border-radius: '15px'
  ha-card-box-shadow: 'inset 0px 0px 2px 2px var(--border-color)'
  ha-card-header-color: 'rgba(255, 255, 255, 1)'
  ############################ STATES AND BADGES ############################
  state-icon-color: 'rgba(0, 0, 0, 1)'
  state-icon-active-color: 'rgba(21, 253, 13, 1)'
  state-icon-unavailable-color: 'var(--disabled-text-color)'
  ########################## BACKGROUND AND SIDEBAR #########################
  primary-background-color: '#fafafa'
  secondary-background-color: '#e5e5e5'
  ############################### SIDEBAR MENU #############################
  sidebar-text-color: 'var(--primary-text-color)'
  sidebar-background-color: 'var(--paper-listbox-background-color)'
  sidebar-icon-color: 'rgba(0, 0, 0, 0.5)'
  sidebar-selected-text-color: 'var(--primary-color)'
  sidebar-selected-icon-color: 'var(--primary-color)'
  sidebar-selected-background-color: 'rgba(0, 0, 0, 1)'
  ################################ CONTROLS ###############################
  switch-checked-color: 'var(--primary-color)'
  switch-unchecked-color: 'var(--accent-color)'
  switch-checked-button-color: 'var(--switch-checked-color, var(--paper-grey-50))'
  switch-checked-track-color: 'var(--switch-checked-color, #000000)'
  switch-unchecked-button-color: 'var(--switch-unchecked-color, var(--paper-grey-50))'
  switch-unchecked-track-color: 'var(--switch-unchecked-color, #000000)'
  slider-color: 'var(--primary-color)'
  slider-secondary-color: 'var(--light-primary-color)'
  slider-bar-color: 'var(--disabled-text-color)'
  ############################# FOR LABEL BADGE ############################
  label-badge-background-color: 'white'
  label-badge-text-color: 'rgb(76, 76, 76)'
  label-badge-red: '#DF4C1E'
  label-badge-blue: '#039be5'
  label-badge-green: '#0DA035'
  label-badge-yellow: '#f4b400'
  label-badge-grey: 'var(--paper-grey-500)'
#################################
# Paper-styles color.html dependency is stripped on build.
# When a default paper-style color is used, it needs to be copied
# from paper-styles/color.html to here.
#################################
  paper-grey-50: '#fafafa' # default for: --mwc-switch-unchecked-button-color
  paper-grey-200: '#eeeeee' # for ha-date-picker-style
  paper-grey-500: '#9e9e9e' # --label-badge-grey
#################################
# for paper-spinner
#################################
  google-red-500: '#db4437'
  google-blue-500: '#4285f4'
  google-green-500: '#0f9d58'
  google-yellow-500: '#f4b400'
  paper-spinner-color: 'var(--primary-color)'
#################################
# for paper-slider
#################################
  paper-green-400: '#66bb6a'
  paper-blue-400: '#42a5f5'
  paper-orange-400: '#ffa726'
#################################
# opacity for dark text on a light background
#################################
  dark-divider-opacity: '0.12'
  dark-disabled-opacity: '0.38' #or hint text or icon
  dark-secondary-opacity: '0.54'
  dark-primary-opacity: '0.87'
#################################
# opacity for light text on a dark background
#################################
  light-divider-opacity: '0.12'
  light-disabled-opacity: '0.3' # or hint text or icon
  light-secondary-opacity: '0.7'
  light-primary-opacity: '1.0'
#################################
# derived colors, to keep existing themes mostly working
#################################
  paper-card-background-color: 'rgba(0, 0, 0, 1)'
  paper-listbox-background-color: 'rgba(0, 0, 0, 1)'
  paper-item-icon-active-color: 'rgba(0, 0, 0, 1)'
  paper-item-icon-color: 'rgba(0, 0, 0, 1)'
  table-row-alternative-background-color: 'rgba(166, 0, 255, 1)'
  table-row-background-color: 'rgba(166, 0, 255, 1)'
#################################
# set our slider style
#################################
  paper-slider-knob-color: 'var(--slider-color)'
  paper-slider-knob-start-color: 'var(--slider-color)'
  paper-slider-pin-color: 'var(--slider-color)'
  paper-slider-active-color: 'var(--slider-color)'
  paper-slider-secondary-color: 'var(--slider-secondary-color)'
  paper-slider-container-color: 'var(--slider-bar-color)'
  ha-paper-slider-pin-font-size: '55px'
#################################
# set data table style
#################################
  data-table-background-color: 'var(--card-background-color)'
#################################
# Change some parts in developer tools
#################################
  paper-dialog-background-color: 'rgba(0,255,0,1)'
  paper-dialog-color: 'rgba(0, 0, 0, 1)'
#################################
# rgb
#################################
  rgb-primary-color: 'rgb(3, 169, 244)'
  rgb-accent-color: 'rgb(255, 152, 0)'
  rgb-primary-text-color: 'rgb(33, 33, 33)'
  rgb-secondary-text-color: 'rgb(114, 114, 114)'
  rgb-text-primary-color: 'rgb(255, 255, 255)'
#################################
# mwc
#################################
  mdc-theme-primary: 'rgba(0, 0, 0, 1)'
  mdc-theme-secondary: 'var(--accent-color)'
  mdc-theme-background: 'var(--primary-background-color)'
  mdc-theme-surface: 'var(--paper-card-background-color, var(--card-background-color))'
#################################
# mwc text styles
#################################
  mdc-theme-on-primary: 'var(--text-primary-color)'
  mdc-theme-on-secondary: 'var(--text-primary-color)'
  mdc-theme-on-surface: 'var(--primary-text-color)'
#################################
# app header background color
#################################
  app-header-background-color: 'rgba(0, 0, 255, 1)'
  app-header-text-color: 'var(--text-primary-color)'
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
# BLACK --------> #000000
# WHITE --------> #FFFFFF
# GRAY(S) ------> Lighter: #202020                    ---------------> Middle Range #727272                      ---------------> Darker: #383838 
# ORANGE(S) ----> #DD5800                             ---------------> 
# GREEN(S) -----> #00FF3C                             --------------->
# BLUE(S) ------>                                     ---------------> 
# RED(S) -------> Red: #FF0000 rgba(255, 0, 0, 1)     ---------------> Burgundyish: #900C3F rgba(144, 12, 63, 1) ---------------> 
# YELLOW(S) ----> #F7FF00                             ---------------> 
# PURPLE(S) ---->                                     ---------------> 
# BROWN(S) ----->                                     ---------------> 