###########################################
###########################################
###########################################
############### history.yaml ##############
###########################################
include:
  entities:
    - binary_sensor.left_guest_bedroom_window
    - binary_sensor.right_guest_bedroom_window
    - binary_sensor.right_living_room_window
    - binary_sensor.left_living_room_window
    - binary_sensor.kitchen_window
    - binary_sensor.hallway_bathroom_window
    - binary_sensor.master_bathroom_window
    - binary_sensor.nursery_window
    - binary_sensor.front_door
    - binary_sensor.back_door
    - lock.front_door_deadbolt
    #######################################
    - binary_sensor.living_room_motion
    - binary_sensor.kitchen_motion
    - binary_sensor.master_bedroom_closet_motion
    - binary_sensor.nursery_motion
    - binary_sensor.driveway_motion
    - binary_sensor.crib_motion
    #######################################
    - sensor.speed_test_upload
    - sensor.speed_test_download
#    - sensor.speed_test_ping
    #######################################
    - sensor.ios_tde_steps
    - sensor.ios_sdm_steps
###########################################
############-----> Energy <-----###########
    - sensor.energy_usage_daily
    - sensor.energy_usage_monthly
    - sensor.energy_usage_quarterly
    - sensor.energy_usage_annually
    - sensor.duke_energy_cost_daily
    - sensor.duke_energy_cost_monthly
    - sensor.duke_energy_cost_quarterly
    - sensor.duke_energy_cost_annually
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###