###########################################
###########################################
###########################################
############### logbook.yaml ##############
###########################################

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###
# https://companion.home-assistant.io/docs/notifications/actionable-notifications