###########################################
###########################################
###########################################
############### logbook.yaml ##############
###########################################
exclude:
  domains:
    - automation
#    - binary_sensor
#    - device_tracker
    - group
    - media_player
    - script
    - sensor
#    - switch
    - weather 
    - zwave
###########################################
###########################################
###########################################
include:
  domains:
    - person
    - light
    - switch
    - binary_sensor
  #  - sensor
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###