###########################################
###########################################
###########################################
############### logger.yaml ###############
###########################################
# LOGLEVELS
# - critical
# - fatal
# - error
# - warning
# - warn
# - info
# - debug
# - notset
###########################################

default: warning
#logs:
#  homeassistant.components.mqtt: debug
#  homeassistant.components.zwave: debug
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###