###########################################
###########################################
###########################################
################ mqtt.yaml ################
###########################################
broker: core-mosquitto
port: 1883
discovery: true
birth_message:
  topic: 'homeassistant/status'
  payload: 'online'
will_message:
  topic: 'homeassistant/status'
  payload: 'offline'
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###