###########################################
###########################################
###########################################
########### panel_iframes.yaml ############
###########################################
#grocy_02:
#  title: Grocey 02
#  icon: mdi:cart
#  url: http://10.1.50.249:80
#  require_admin: false
###########################################
#ssh_terminal:
#  title: Terminal
#  icon: mdi:ssh
#  url: http://10.1.50.249:22
#  require_admin: true
###########################################
#glances:
#  title: Glances
#  icon: mdi:ubuntu
#  url: http://10.1.50.249:8086
#  require_admin: true
###########################################
#motion_eye:
#  title: Surveillance
#  icon: mdi:cctv
#  url: http://10.1.50.249:80
#  require_admin: false
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###