###########################################
###########################################
###########################################
######### zwave_device_config.yaml ########
###########################################
#binary_sensor.driveway_sensor_motion:
#  ignored: false
#  polling_intensity: 0
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###