####################################################################################################
####################################################################################################
####################################################################################################
####################################### GENERIC: Transparent #######################################
Scripts: https://cdn.iconscout.com/icon/premium/png-256-thumb/programming-script-503834.png
CVS_Pharmacy: https://logok.org/wp-content/uploads/2015/08/CVS-pharmacy-logo.png
Lowes: https://cdn.freebiesupply.com/logos/large/2x/lowes-logo-png-transparent.png
Petsmart: https://cdn.freebiesupply.com/logos/large/2x/petsmart-1-logo-png-transparent.png
Bilo: https://cdn.freebiesupply.com/logos/large/2x/bi-lo-logo-png-transparent.png
Fire_Department: https://banner2.cleanpng.com/20180315/cie/kisspng-firefighter-volunteer-fire-department-sticker-deca-fire-hat-cliparts-vector-5aaaa677f02621.1869575815211331759837.jpg
Police_Station: https://p7.hiclipart.com/preview/326/648/933/badge-police-officer-lapel-pin-police-badge-png-clip-art.jpg
Walmart: https://banner2.cleanpng.com/20180201/hiw/kisspng-walmart-logo-advertising-coupon-clip-art-walmart-vertical-logo-5a737a86ecbb87.6954179015175174469697.jpg
Home_ARRIVED: https://cdn4.iconfinder.com/data/icons/logistics-and-delivery-vol-2/64/destination-512.png
vanguard_logo_black_letters: https://lh3.googleusercontent.com/proxy/Prd_S40n9YBDmXQn9FzT9_xWDJwD6V0mA6x-XQL-U1qJ-rERzx6pk07kvsTEJtHWhUy_UfiXp0pDHO_ElJDIkmu-BobyzcgRku2LZh5PK6GR-C4xh0uKt6Eq0JER-mYGiA
vanguard_logo_red_letters: https://www.fixedincomenews.com.au/wp-content/uploads/2020/03/vanguardlogo.png
tombstone: https://p7.hiclipart.com/preview/19/983/650/headstone-cemetery-clip-art-creative-halloween-tombstone.jpg
AWC_Atomic_Wallet_Coin: https://atomicwallet.io/wp-content/uploads/2020/09/atomic_wallet_logo_dark_rounded_2.png
Yearn_Finance_YFY: https://cryptologos.cc/logos/yearn-finance-yfi-logo.png


####################################################################################################
####################################################################################################
####################################################################################################
##################################### GENERIC: Non-Transparent #####################################
hikivision_cctv: https://static.bhphoto.com/images/images500x500/1501094111_1346617.jpg
money_02: https://media1.tenor.com/images/9427062a3f6ce90eea2cc15aa9243b98/tenor.gif




####################################################################################################
####################################################################################################
####################################################################################################
###################################### ANIMATED & TRANSPARENT ######################################
####################################################################################################
washing_machine: https://media2.giphy.com/media/1qdhN1zxK0sf752Ii5/giphy.gif
led_strip_animated_transparent_gif: https://ksr-ugc.imgix.net/assets/012/946/791/cce98ac82433aec9bba5efcdb489e645_original.gif?w=680&fit=max&v=1467593643&q=92&s=22a1fb429cd87f57936f0fd35b6afaa8
ceiling_fan: https://members.tripod.com/~HANDING/MOVING_FAN_2.gif
earth_01: https://i.pinimg.com/originals/0d/c9/68/0dc968448592a7d533096b74c263cc40.gif
wifi_online: https://telsys.co.za/wp-content/uploads/2019/10/wifi.gif
www_online: https://i.gifer.com/YIgb.gif
money_01: https://media1.giphy.com/media/9xttQuH2oHGIEDHt4v/source.gif
money_03: https://i.pinimg.com/originals/1a/e0/0f/1ae00f4fd7befd750e5b78b3e3c9d4e3.gif
