###########################################
###########################################
###########################################
#### tde_sdm_mf_front_door_locked.yaml ####
###########################################

- alias: '[iOS_Sounds] Front Door: Locked'
  trigger:
    - platform: state
      entity_id: lock.front_door_deadbolt
      to: 'locked'
  action:
    service: notify.ios_tde_sdm
    data:
      message: “Front Door Has Been Locked”
      data:
        push:
          sound: "US-EN-Morgan-Freeman-Front-Door-Locked.wav"

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
