###########################################
###########################################
###########################################
#### tde_sdm_mf_front_door_opened.yaml ####
###########################################

- alias: '[iOS_Sounds] Front Door: Opened'
  trigger:
    - platform: state
      entity_id: binary_sensor.front_door
      to: 'on'
  action:
    service: notify.ios_tde_sdm
    data:
      message: “Front Door Has Opened”
      data:
        push:
          sound: "US-EN-Morgan-Freeman-Front-Door-Opened"

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
