###########################################
###########################################
###########################################
############## flux_led.yaml ##############
###########################################

#- platform: flux_led
#  automatic_add: true

- platform: flux_led
  scan_interval: 0.5
  devices:
    10.1.1.121:
      name: Right Nursery Shelf
      mode: rgb
    10.1.1.122:
      name: Left Nursery Shelf
      mode: rgb

###########################################
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################