###########################################
###########################################
###########################################
########## flume_flow_status.yaml #########
###########################################
- platform: template
  sensors:
    flume_flow_status:
      friendly_name: "Flume Flow Status"
      value_template: >-
        {{ states.sensor.home_water_meter_usage_now.state != "0" }}
###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################
###########################################
###########################################
###---------> USEFUL RESOURCES <--------###