###########################################
###########################################
###########################################
########## wemos_05_mbr_pir.yaml ##########
###########################################

- platform: mqtt
  name: Master Bedroom Motion
  state_topic: Wemos_05/stat/PIR1
  payload_on: "ON"
  payload_off: "OFF"
  device_class: motion
  off_delay: 5
###########################################
# Rule1 on Switch2#state=1 do publish Wemos_05/stat/PIR1 ON endon on Switch2#state=0 do Publish Wemos_05/stat/PIR1 OFF endon

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################