###########################################
###########################################
###########################################
####### zwave_driveway_sensor.yaml ########
###########################################

platform: template
sensors:
  driveway_motion_sensor_battery_low:
    friendly_name: "Driveway Motion Sensor Low Battery"
    value_template: "{{ states('sensor.driveway_sensor_battery_level') | float < 25 }}"

  driveway_motion:
    friendly_name: "Driveway Motion Sensor"
    device_class: motion
    value_template: "{{ states('sensor.driveway_sensor_burglar', '8') }}"

###########################################
###----> END OF CONFIGURATION FILE <----###
###########################################